CREATE DATABASE IF NOT EXISTS COLLEGE ;

USE COLLEGE ;
DROP TABLE STUDENT;

CREATE TABLE TEACHER (
TEACH_ID INT PRIMARY KEY,
TEACH_NAME VARCHAR (50)
);
 
CREATE TABLE IF NOT EXISTS STUDENT (
ROLL_NO INT PRIMARY KEY ,
STD_NAME VARCHAR(50)NOT NULL,
MARKS INT NOT NULL,
ID INT NOT NULL,
FOREIGN KEY (ID) REFERENCES TEACHER(TEACH_ID)
);
INSERT INTO STUDENT VALUES 
 (1,'CHETAN',78,101),
 (2,'GANESH',80,103),
 (3,'DIVAKAR',73,105),
 (4,'KUNDAN',85,102),
 (5,'ISHWAR',92,101),
 (6,'ANIKET',96,103),
SELECT * FROM STUDENT ;
DROP TABLE IF EXISTS TEACHER ;

INSERT INTO TEACHER VALUES 
(101,'AISHWARYA'),
(102,'SWATI'),
(103,'PARATIMA'),
(104,'DEEPAK'),
(105,'REKHA');
SELECT *FROM  TEACHER;
